config/routes.rb
Rails.application.routes.draw do
    devise_for :users
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    devise_scope :user do
        authenticated :user do
            root to: 'dashboards#index'

            resources :dashboards, only: %i[index]
            get '/news', to: 'dashboards#news', as: :dashboard_news
            get '/library', to: 'dashboards#library', as: :dashboard_library
            get '/new', to: 'dashboards#new', as: :dashboard_new

            resources :users, only: %i[index show edit update] do
                resources :user_bookmarks, only: %i[index]
            end

            resources :books, only: %i[index show new create edit update destroy] do
                get '/read', to: 'books#read', as: :read
                get '/section/:section_id/read', to: 'books#read_section', as: :read_section
                resources :book_translators, only: %i[new create destroy]
                resources :book_authors, only: %i[new create destroy]
                resources :book_genres, only: %i[new create destroy]

                resources :book_sections, only: %i[index new create edit update destroy] do
                    get '/list', to: 'book_sections#list', as: :edit_list
                    resources :translated_texts, only: %i[create show update destroy]
                    resources :materials, only: %i[new create update destroy]
                end
            end

            resources :original_images, only: %i[update]
            resources :original_texts, only: %i[update]

            resources :user_bookmarks, only: %i[create destroy]

            resources :book_ratings, only: %i[create destroy]
        end

        unauthenticated :user do
            root to: 'devise/sessions#new'
        end
    end
end

app/models/book_genre.rb
class BookGenre < ApplicationRecord
    belongs_to :book, foreign_key: :book_id
    belongs_to :genre, foreign_key: :genre_id

    validates :genre_id, presence: true, on: %i[update create]

    validates_uniqueness_of :book_id, scope: :genre_id, on: %i[update create]

    attr_accessor :genre_name
end

app/controllers/book_genres_controller.rb
class BookGenresController < ApplicationController
    before_action :get_book, only: %i[new create destroy]
    before_action :is_creator?, only: %i[new create destroy]

    def new
        @book_genre = BookGenre.new(book_id: @book.id)
        genres = Genre.all.pluck(:name)
        @genres = genres.as_json(only: %i[id name])
    end

    def create
        @book_genre = BookGenre.new(book_genres_params)
        if @book_genre.save
            flash[:notice] = 'Жанр успешно добавлен'
            redirect_to(edit_book_path(@book.id)) && return
        else
            flash.now[:notice] = @book_genre.errors.full_messages.join(', ')
        end
        respond_to do |format|
            format.js
        end
    end

    def destroy
        @book_genre = BookGenre.find(params[:id])
        @id = @book_genre.genre_id
        if @book_genre.destroy
            @notice_type = 'success'
            @book_genre_destroy = true
            flash.now[:notice] = 'Жанр успешно удален'
        else
            @notice_type = 'danger'
            @book_genre_destroy = false
            flash.now[:notice] = @book_genre.errors.full_messages.join(', ')
        end
        respond_to do |format|
            format.js
        end
    end

    private

    def book_genres_params
        name = params[:book_genre][:genre_name]
        genre_id = params[:book_genre][:genre_id]
        genre_id = Genre.find_by(name: name).id unless name.blank?
        params.require(:book_genre).permit(:id, :book_id, :genre_id).merge(genre_id: genre_id)
    end

    def get_book
        @active_books = true
        @book = Book.find(params[:book_id])
        raise ActionController::RoutingError, with: -> { render_404 } if @book.nil?
    end

    def is_creator?
        raise ActionController::RoutingError, with: -> { render_404 } if @book.user_id != current_user.id
    end
end

app/views/book_genres/create.js.erb
$.notify({
  message: '<%= flash[:notice] %>'
},{
	type: 'danger',
  delay: 2000,
  timer: 1000
});

app/views/book_genres/destroy.js.erb
$.notify({
  message: '<%= flash[:notice] %>'
},{
	type: '<%= @notice_type %>',
  delay: 2000,
  timer: 1000
});

<% if @book_genre_destroy %>
    console.log($("#genre_<%= @id %>"))
    $("#genre_<%= @id %>").remove()
<% end %>

app/views/book_genres/new.html.erb
<div class="container">
  <div class='row'>
    <div class='col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12'>
      <div class='linked-line'>
        <a class='linked-link left'>Добавить жанр</a>
        <%= link_to edit_book_path(@book.id), class: 'linked-link right' do %>Назад<% end %>
      </div>
    </div>
    <div class='col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12'>
      <%= form_for(@book_genre, url: book_book_genres_path(@book.id), method: :post, remote: true) do |f| %>
        <div class='form-row'>
          <div class="form-group col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
            <%= f.label :genre_name, 'Жанр' %>
            <%= f.text_field :genre_name, class: "form-control typeahead", placeholder: 'Начните вводить (например: Фэнтези)', autocomplete: "off" %>
          </div>
          <%= f.hidden_field :id %>
          <%= f.hidden_field :book_id, value: @book.id %>
        </div>
        <div class='form-row'>
          <div class="form-group col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
            <%= f.button :submit, class: 'btn btn-primary btn-block' do %>
              Добавить
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script>
    $(function () {
        let genreData = <%= @genres.to_json.html_safe %>
        $(".typeahead").typeahead({
            source: genreData
        });
    })
</script>