config/routes.rb
Rails.application.routes.draw do
    devise_for :users
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    devise_scope :user do
        authenticated :user do
            root to: 'dashboards#index'

            resources :dashboards, only: %i[index]
            get '/news', to: 'dashboards#news', as: :dashboard_news
            get '/library', to: 'dashboards#library', as: :dashboard_library
            get '/new', to: 'dashboards#new', as: :dashboard_new

            resources :users, only: %i[index show edit update] do
                resources :user_bookmarks, only: %i[index]
            end

            resources :books, only: %i[index show new create edit update destroy] do
                get '/read', to: 'books#read', as: :read
                get '/section/:section_id/read', to: 'books#read_section', as: :read_section
                resources :book_translators, only: %i[new create destroy]
                resources :book_authors, only: %i[new create destroy]
                resources :book_genres, only: %i[new create destroy]

                resources :book_sections, only: %i[index new create edit update destroy] do
                    get '/list', to: 'book_sections#list', as: :edit_list
                    resources :translated_texts, only: %i[create show update destroy]
                    resources :materials, only: %i[new create update destroy]
                end
            end

            resources :original_images, only: %i[update]
            resources :original_texts, only: %i[update]

            resources :user_bookmarks, only: %i[create destroy]

            resources :book_ratings, only: %i[create destroy]
        end

        unauthenticated :user do
            root to: 'devise/sessions#new'
        end
    end
end

app/models/book_translator.rb
class BookTranslator < ApplicationRecord
    belongs_to :user, foreign_key: :user_id
    belongs_to :book, foreign_key: :book_id
    belongs_to :translator_type, foreign_key: :translator_type_id

    validates :book_id, presence: true, on: %i[update create]
    validates :user_id, presence: true, on: %i[update create]
    validates :translator_type_id, presence: true, on: %i[update create]

    validates_uniqueness_of :user_id, scope: :book_id, on: %i[update create]

    attr_accessor :translator_email
end

app/controllers/book_translators_controller.rb
class BookTranslatorsController < ApplicationController
    before_action :get_book, only: %i[new create destroy]
    before_action :is_creator?, only: %i[new create destroy]

    def new
        @book_translator = BookTranslator.new(book_id: @book.id)
        @translator_types = TranslatorType.where.not(id: 1)
    end

    def create
        @book_translator = BookTranslator.new(book_translators_params)
        if @book_translator.save
            flash[:notice] = 'Переводчик успешно добавлен'
            redirect_to(edit_book_path(@book.id)) && return
        else
            flash.now[:notice] = @book_translator.errors.full_messages.join(', ')
        end
        respond_to do |format|
            format.js
        end
    end

    def destroy
        @book_translator = BookTranslator.find(params[:id])
        @id = @book_translator.user_id
        if @book_translator.destroy
            @notice_type = 'success'
            @book_translator_destroy = true
            flash.now[:notice] = 'Переводчик успешно удален'
        else
            @notice_type = 'danger'
            @book_translator_destroy = false
            flash.now[:notice] = @book_translator.errors.full_messages.join(', ')
        end
        respond_to do |format|
            format.js
        end
    end

    private

    def book_translators_params
        user = User.find_by(email: params[:book_translator][:translator_email])
        user_id = nil
        user_id = user.id unless user.nil?
        params.require(:book_translator).permit(:id, :user_id, :book_id, :translator_type_id).merge(user_id: user_id)
    end

    def get_book
        @active_books = true
        @book = Book.find(params[:book_id])
        raise ActionController::RoutingError, with: -> { render_404 } if @book.nil?
    end

    def is_creator?
        raise ActionController::RoutingError, with: -> { render_404 } if @book.user_id != current_user.id
    end
end

app/views/book_translators/create.js.erb
$.notify({
  message: '<%= flash[:notice] %>'
},{
	type: 'danger',
  delay: 2000,
  timer: 1000
});

app/views/book_translators/destroy.js.erb
$.notify({
  message: '<%= flash[:notice] %>'
},{
	type: '<%= @notice_type %>',
  delay: 2000,
  timer: 1000
});

<% if @book_translator_destroy %>
    console.log($("#translator_<%= @id %>"))
    $("#translator_<%= @id %>").remove()
<% end %>

app/views/book_translators/new.html.erb
<div class="container">
  <div class='row'>
    <div class='col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12'>
        <div class='linked-line'>
          <a class='linked-link left'>Добавить переводчика</a>
          <%= link_to edit_book_path(@book.id), class: 'linked-link right' do %>Назад<% end %>
        </div>
    </div>
    <div class='col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12'>
      <%= form_for(@book_translator, url: book_book_translators_path(@book.id), method: :post, remote: true) do |f| %>
        <div class='form-row'>
            <div class="form-group col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
              <%= f.label :translator_email, 'E-mail' %>
              <%= f.email_field :translator_email, placeholder: 'E-mail', class: 'form-control' %>
            </div>
            <div class="form-group col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
              <%= f.label :translator_type_id, 'Роль' %>
              <%= f.select(:translator_type_id, @translator_types.map{|s| [s.name,s.id]}, {}, class: 'form-control') %>
            </div>
            <%= f.hidden_field :id %>
            <%= f.hidden_field :book_id %>
        </div>
        <div class='form-row'>
          <div class="form-group col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
            <%= f.button :submit, class: 'btn btn-primary btn-block' do %>
              Добавить
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>