config/routes.rb
Rails.application.routes.draw do
    devise_for :users
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    devise_scope :user do
        authenticated :user do
            root to: 'dashboards#index'

            resources :dashboards, only: %i[index]
            get '/news', to: 'dashboards#news', as: :dashboard_news
            get '/library', to: 'dashboards#library', as: :dashboard_library
            get '/new', to: 'dashboards#new', as: :dashboard_new

            resources :users, only: %i[index show edit update] do
                resources :user_bookmarks, only: %i[index]
            end

            resources :books, only: %i[index show new create edit update destroy] do
                get '/read', to: 'books#read', as: :read
                get '/section/:section_id/read', to: 'books#read_section', as: :read_section
                resources :book_translators, only: %i[new create destroy]
                resources :book_authors, only: %i[new create destroy]
                resources :book_genres, only: %i[new create destroy]

                resources :book_sections, only: %i[index new create edit update destroy] do
                    get '/list', to: 'book_sections#list', as: :edit_list
                    resources :translated_texts, only: %i[create show update destroy]
                    resources :materials, only: %i[new create update destroy]
                end
            end

            resources :original_images, only: %i[update]
            resources :original_texts, only: %i[update]

            resources :user_bookmarks, only: %i[create destroy]

            resources :book_ratings, only: %i[create destroy]
        end

        unauthenticated :user do
            root to: 'devise/sessions#new'
        end
    end
end

app/models/material.rb
class Material < ApplicationRecord

    belongs_to :materialable, polymorphic: true, dependent: :destroy

    belongs_to :book_section, foreign_key: :book_section_id

    validates :book_section_id, presence: true, on: %i[update create]

    attr_accessor :material_type
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
    before_action :get_book_section
    before_action :is_creator?

    def new
        @material = Material.new(book_section_id: @section.id)
        @position = 1
        materials = @section.materials.order(:position)
        @position += materials.last.position unless materials.blank?
    end

    def create
        @material_type = params[:material][:material_type]
        @material = if @material_type == 'text'
                        @section.original_texts.create(materials_params)
                    else
                        @section.original_images.create(materials_params)
                    end
        if @material.id.nil?
            flash.now[:notice] = @material.errors.full_messages.join(', ')
        else
            flash[:notice] = 'Фрагмент успешно добавлен'
            redirect_to(book_book_section_edit_list_path(@book.id, @section.id)) && return
        end
        respond_to do |format|
            format.js
        end
    end

    def update; end

    def destroy; end

    private

    def materials_params
        params.require(:material).permit(:position, :book_section_id)
    end

    def get_book_section
        @active_books = true
        @book = Book.find(params[:book_id])
        @section = @book.book_sections.find(params[:book_section_id])

        raise ActionController::RoutingError, with: -> { render_404 } if @book.nil? || @section.nil?
    end

    def is_creator?
        # Разрешение на удаление, изменение, создание
        raise ActionController::RoutingError, with: -> { render_404 } if @book.user_id != current_user.id
    end

    def is_translator?
        translator = @book.book_translators.find_by(user_id: current_user.id)
        raise ActionController::RoutingError, with: -> { render_404 } if translator.nil?
    end
end

app/views/materials/edit/_original_image.html.erb
<tr class='row m-0 material-<%= image.material.id %> material-edit'>
  <th class="col-1 col-sm-1 col-md-1 col-lg-1 col-xl-1 d-flex justify-content-center" scope="row"><%= image.position %></th>
  <td class="col-11 col-sm-11 col-md-11 col-lg-11 col-xl-11" colspan='2'>
    <% if @book.is_creator?(current_user.id) %>
      <%= form_for(image, url: original_image_path(image.id), method: :put, remote: true, class: 'col s12' ) do |f| %>
        <div class="book-cover">
          <div class="cover-image">
            <div class='dynamic-data'>
              <%= image_tag image.images.url(:cover), class: 'image_preview', onclick: "change_cover('original_image_images_#{image.id}');" %>
            </div>
            <%= f.file_field :images, accept: 'image/jpeg,image/png,image/bmp,image/jpeg', class: 'image ajax-cover', id: "original_image_images_#{image.id}" %>
            <%= f.label :images, 'Выберите файл с изображением', class:'', for: "original_image_images_#{image.id}" %>
            <%= f.hidden_field :id %>
            <%= f.hidden_field :position %>
            <%= f.hidden_field :book_section_id %>
          </div>
        </div>
      <% end %>
    <% else %>
      <div class="book-cover">
        <div class="cover-image">
          <div class='dynamic-data'>
            <%= image_tag image.images.url(:cover), class: 'image_preview' %>
          </div>
        </div>
      </div>
    <% end %>
  </td>
</tr>

app/views/materials/edit/_original_text.html.erb
<tr class='row m-0 material-<%= text.material.id %> material-edit'>
  <th class="col-1 col-sm-1 col-md-1 col-lg-1 col-xl-1 d-flex justify-content-center" scope="row"><%= text.position %></th>
  <td class="col-6 col-sm-6 col-md-6 col-lg-6 col-xl-6">
    <% if @book.is_creator?(current_user.id) %>
      <%= form_for(text, url: original_text_path(text.id), method: :put, remote: true, class: 'col s12' ) do |f| %>
        <%= f.text_area :text, class: 'editor', id: "original_text_text_#{text.id}" %>
        <%= f.hidden_field :id %>
        <%= f.hidden_field :position %>
        <%= f.hidden_field :book_section_id %>
      <% end %>
    <% else %>
      <div class='col s12 m12 l12 no-editor'><%= text.text.html_safe %></div>
    <% end %>
  </td>
  <td class="col-5 col-sm-5 col-md-5 col-lg-5 col-xl-5">
    <div class='row m-0'>
    <%= link_to book_book_section_translated_texts_path(@book.id, @section.id, :original_text_id => text.id), method: :post, remote: true, class: 'btn btn-outline-info btn-block', role: 'button' do %>
      Добавить перевод
    <% end %>
    </div>
    <div class='row m-0'>
        <%= render :partial => 'materials/edit/translation_list_item', :collection => text.translated_texts.order(:created_at), as: :translated %>
    </div>
  </td>
</tr>

app/views/materials/edit/_translation_list_item.html.erb
<div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 translated_text-line">
  <%= link_to translation_info(translated), book_book_section_translated_text_path(@book.id, @section.id, translated.id), class: 'translated_text-link link' %>
  <% if translated.is_main %>
    <span class='translated_text-link status'>основной</span>
  <% end %>
</div>